/**
 * Sample listings used by prisma/seed.ts.
 *
 * `photos` are Unsplash photo IDs; the seed script downloads each one into
 * storage/uploads so the demo runs without depending on an external CDN at
 * request time.
 */
export type SeedProperty = {
  title: string;
  description: string;
  type: "APARTMENT" | "VILLA" | "PLOT" | "COMMERCIAL";
  listingType: "RENT" | "SALE";
  price: number;
  deposit?: number;
  city: string;
  locality: string;
  address?: string;
  pincode?: string;
  bedrooms: number;
  bathrooms: number;
  areaSqft: number;
  furnishing?: string;
  floor?: string;
  ageYears?: number;
  amenities: string[];
  featured?: boolean;
  /** Which seeded user owns it: "owner" | "agent". */
  owner: "owner" | "agent";
  photos: string[];
};

export const SEED_PROPERTIES: SeedProperty[] = [
  {
    title: "Spacious 3 BHK with lake view in Powai",
    description:
      "A bright, cross-ventilated 3 BHK on a high floor overlooking Powai lake. The living room opens onto a wide balcony, and both bedrooms get morning sun. The society has a clubhouse, gym and 24x7 security, with Hiranandani Gardens and D-Mart a five-minute walk away.\n\nTwo covered parking slots included. Ready to move in.",
    type: "APARTMENT",
    listingType: "SALE",
    price: 32500000,
    city: "Mumbai",
    locality: "Powai",
    address: "Lake Homes, Chandivali Farm Road",
    pincode: "400076",
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1650,
    furnishing: "Semi-Furnished",
    floor: "14 of 22",
    ageYears: 6,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Swimming Pool", "Gymnasium", "Security", "Clubhouse"],
    featured: true,
    owner: "owner",
    photos: ["1522708323590-d24dbb6b0267", "1560448204-e02f11c3d0e2", "1560185007-cde436f6a4d0", "1502672260266-1c1ef2d93688"],
  },
  {
    title: "Sea-facing 2 BHK on Carter Road, Bandra West",
    description:
      "Rare sea-facing 2 BHK in a low-rise building on Carter Road. Wooden flooring throughout, a modular kitchen fitted last year, and an open balcony where you can actually hear the waves. Walking distance to the promenade, cafés and Bandra station.",
    type: "APARTMENT",
    listingType: "RENT",
    price: 185000,
    deposit: 1110000,
    city: "Mumbai",
    locality: "Bandra West",
    pincode: "400050",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1100,
    furnishing: "Fully Furnished",
    floor: "4 of 7",
    ageYears: 12,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Security"],
    featured: true,
    owner: "agent",
    photos: ["1502672260266-1c1ef2d93688", "1493809842364-78817add7ffb", "1522708323590-d24dbb6b0267"],
  },
  {
    title: "4 BHK independent villa with private garden in Whitefield",
    description:
      "A double-storey villa in a gated community of 40 homes. Ground floor has a formal living room, dining area and a guest bedroom; the upper floor holds three bedrooms, all en-suite. The garden runs the full width of the plot and there is covered parking for two cars.\n\nCommunity has a pool, gym and a small park. Fifteen minutes from ITPL.",
    type: "VILLA",
    listingType: "SALE",
    price: 48000000,
    city: "Bengaluru",
    locality: "Whitefield",
    address: "Palm Meadows, Ramagondanahalli",
    pincode: "560066",
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3400,
    furnishing: "Unfurnished",
    ageYears: 9,
    amenities: ["Covered Parking", "Swimming Pool", "Gymnasium", "Security", "Park", "Children's Play Area", "Rain Water Harvesting"],
    featured: true,
    owner: "owner",
    photos: ["1613490493576-7fde63acd811", "1600596542815-ffad4c1539a9", "1600607687939-ce8a6c25118c", "1600585154340-be6161a56a0c"],
  },
  {
    title: "Modern 2 BHK near Indiranagar metro",
    description:
      "Compact, well-planned 2 BHK two minutes from the Indiranagar metro station. Fresh paint, new fittings in both bathrooms, and a covered balcony that works as a study. Ideal for a working couple — 100 Feet Road is a short walk away.",
    type: "APARTMENT",
    listingType: "RENT",
    price: 52000,
    deposit: 312000,
    city: "Bengaluru",
    locality: "Indiranagar",
    pincode: "560038",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1150,
    furnishing: "Semi-Furnished",
    floor: "3 of 5",
    ageYears: 8,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Security", "Gas Pipeline"],
    owner: "agent",
    photos: ["1493809842364-78817add7ffb", "1522708323590-d24dbb6b0267", "1560185007-cde436f6a4d0"],
  },
  {
    title: "Premium 3 BHK in a gated township, Gachibowli",
    description:
      "Corner unit in one of Gachibowli's better-run townships. Three bedrooms with wardrobes, a utility off the kitchen, and a large wrap-around balcony. The township has its own retail street, two pools, a gym and an amphitheatre.\n\nFinancial District is a ten-minute drive.",
    type: "APARTMENT",
    listingType: "SALE",
    price: 14500000,
    city: "Hyderabad",
    locality: "Gachibowli",
    pincode: "500032",
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1780,
    furnishing: "Semi-Furnished",
    floor: "11 of 18",
    ageYears: 4,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Swimming Pool", "Gymnasium", "Clubhouse", "Security", "Children's Play Area"],
    featured: true,
    owner: "owner",
    photos: ["1545324418-cc1a3fa10c00", "1560448204-e02f11c3d0e2", "1502672260266-1c1ef2d93688"],
  },
  {
    title: "Studio apartment for rent in HITEC City",
    description:
      "Furnished studio in a serviced building aimed at working professionals. Comes with a bed, wardrobe, work desk, induction hob and a small fridge. Housekeeping twice a week is included in the rent. Cyber Towers is a seven-minute walk.",
    type: "APARTMENT",
    listingType: "RENT",
    price: 28000,
    deposit: 84000,
    city: "Hyderabad",
    locality: "HITEC City",
    pincode: "500081",
    bedrooms: 0,
    bathrooms: 1,
    areaSqft: 480,
    furnishing: "Fully Furnished",
    floor: "6 of 12",
    ageYears: 3,
    amenities: ["Lift", "Power Backup", "Security", "Gymnasium"],
    owner: "agent",
    photos: ["1560185007-cde436f6a4d0", "1493809842364-78817add7ffb"],
  },
  {
    title: "Residential plot of 2400 sq.ft in Kondhwa",
    description:
      "East-facing corner plot in a DTCP-approved layout with clear title. Compound wall on three sides, water and electricity connections available at the boundary, and a 30-foot approach road. Suitable for a G+2 build.",
    type: "PLOT",
    listingType: "SALE",
    price: 8900000,
    city: "Pune",
    locality: "Kondhwa",
    pincode: "411048",
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 2400,
    amenities: ["Security", "Rain Water Harvesting"],
    owner: "owner",
    photos: ["1500382017468-9049fed747ef", "1416879595882-3373a0480b5b"],
  },
  {
    title: "Bright 3 BHK in Baner with a large terrace",
    description:
      "Top-floor 3 BHK with exclusive access to a 400 sq.ft terrace — the reason most people take this flat. Living and dining are open-plan, the master bedroom has a walk-in wardrobe, and the society is quiet despite being off Baner Road.",
    type: "APARTMENT",
    listingType: "SALE",
    price: 11200000,
    city: "Pune",
    locality: "Baner",
    pincode: "411045",
    bedrooms: 3,
    bathrooms: 2,
    areaSqft: 1420,
    furnishing: "Semi-Furnished",
    floor: "9 of 9",
    ageYears: 5,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Gymnasium", "Security", "Park"],
    owner: "agent",
    photos: ["1560448204-e02f11c3d0e2", "1522708323590-d24dbb6b0267", "1600607687939-ce8a6c25118c"],
  },
  {
    title: "Furnished 2 BHK for rent in Kharadi",
    description:
      "Fully furnished 2 BHK five minutes from EON IT Park. Sofa, dining table, both beds, wardrobes, washing machine and refrigerator all included. The building has a backup generator that actually runs the lifts and common areas.",
    type: "APARTMENT",
    listingType: "RENT",
    price: 38000,
    deposit: 190000,
    city: "Pune",
    locality: "Kharadi",
    pincode: "411014",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 980,
    furnishing: "Fully Furnished",
    floor: "8 of 14",
    ageYears: 6,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Swimming Pool", "Gymnasium", "Security"],
    owner: "owner",
    photos: ["1493809842364-78817add7ffb", "1545324418-cc1a3fa10c00"],
  },
  {
    title: "Builder-floor 3 BHK in Greater Kailash II",
    description:
      "Second-floor builder unit in a quiet GK-II block, with lift and stilt parking. Marble flooring in the living areas, wooden flooring in the bedrooms, and a modular kitchen. Power backup covers the whole flat, not just the lights.",
    type: "APARTMENT",
    listingType: "SALE",
    price: 42000000,
    city: "Delhi",
    locality: "Greater Kailash II",
    pincode: "110048",
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1900,
    furnishing: "Semi-Furnished",
    floor: "2 of 4",
    ageYears: 7,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Security", "Vaastu Compliant"],
    featured: true,
    owner: "agent",
    photos: ["1600585154340-be6161a56a0c", "1600596542815-ffad4c1539a9", "1560448204-e02f11c3d0e2"],
  },
  {
    title: "2 BHK for rent in Saket, walking distance to metro",
    description:
      "Well-maintained 2 BHK in a family building in Saket. Both bedrooms fit a queen bed comfortably, and there is a separate servant's toilet off the kitchen. Select Citywalk and the metro are both under a kilometre.",
    type: "APARTMENT",
    listingType: "RENT",
    price: 45000,
    deposit: 135000,
    city: "Delhi",
    locality: "Saket",
    pincode: "110017",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1050,
    furnishing: "Semi-Furnished",
    floor: "3 of 4",
    ageYears: 15,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Security"],
    owner: "owner",
    photos: ["1502672260266-1c1ef2d93688", "1493809842364-78817add7ffb"],
  },
  {
    title: "Luxury 4 BHK on Golf Course Road, Gurgaon",
    description:
      "High-floor 4 BHK in a landmark tower on Golf Course Road, with views over the golf course from three rooms. Imported fittings throughout, a private lift lobby, and four covered parking slots. Concierge, spa and a 25m lap pool in the building.",
    type: "APARTMENT",
    listingType: "SALE",
    price: 78000000,
    city: "Gurgaon",
    locality: "Golf Course Road",
    pincode: "122002",
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 4100,
    furnishing: "Semi-Furnished",
    floor: "23 of 30",
    ageYears: 3,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Swimming Pool", "Gymnasium", "Clubhouse", "Security", "Park"],
    featured: true,
    owner: "agent",
    photos: ["1545324418-cc1a3fa10c00", "1600607687939-ce8a6c25118c", "1600585154340-be6161a56a0c", "1560448204-e02f11c3d0e2"],
  },
  {
    title: "3 BHK for rent in DLF Phase 3",
    description:
      "Corner 3 BHK with two balconies in a well-run DLF Phase 3 society. Kitchen has a chimney, hob and water purifier installed. Ten minutes from Cyber Hub and right next to the Phase 3 rapid metro station.",
    type: "APARTMENT",
    listingType: "RENT",
    price: 62000,
    deposit: 186000,
    city: "Gurgaon",
    locality: "DLF Phase 3",
    pincode: "122010",
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1620,
    furnishing: "Semi-Furnished",
    floor: "12 of 19",
    ageYears: 8,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Swimming Pool", "Gymnasium", "Security", "Children's Play Area"],
    owner: "owner",
    photos: ["1560448204-e02f11c3d0e2", "1522708323590-d24dbb6b0267"],
  },
  {
    title: "Ready-to-move 2 BHK in Noida Sector 137",
    description:
      "South-facing 2 BHK in a completed and occupied tower — no possession risk. Modular kitchen, wardrobes in both bedrooms, and a balcony off the living room facing the internal park. Noida-Greater Noida expressway is a two-minute drive.",
    type: "APARTMENT",
    listingType: "SALE",
    price: 7800000,
    city: "Noida",
    locality: "Sector 137",
    pincode: "201305",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1075,
    furnishing: "Semi-Furnished",
    floor: "7 of 21",
    ageYears: 5,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Swimming Pool", "Gymnasium", "Security", "Park", "Gas Pipeline"],
    owner: "agent",
    photos: ["1493809842364-78817add7ffb", "1545324418-cc1a3fa10c00", "1502672260266-1c1ef2d93688"],
  },
  {
    title: "Commercial office space, 2200 sq.ft in Sector 62 Noida",
    description:
      "Fitted-out office on the fourth floor of a Grade-A building in Sector 62. Currently laid out as 32 workstations, four cabins and a meeting room, with a pantry and two washrooms. Central air conditioning and 100% power backup.\n\nAvailable on a three-year lease with a standard escalation clause.",
    type: "COMMERCIAL",
    listingType: "RENT",
    price: 165000,
    deposit: 990000,
    city: "Noida",
    locality: "Sector 62",
    pincode: "201309",
    bedrooms: 0,
    bathrooms: 2,
    areaSqft: 2200,
    furnishing: "Fully Furnished",
    floor: "4 of 9",
    ageYears: 10,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Security"],
    owner: "agent",
    photos: ["1497366754035-f200968a6e72", "1497366811353-6870744d04b2", "1524758631624-e2822e304c36"],
  },
  {
    title: "3 BHK sea-view apartment in Besant Nagar",
    description:
      "Third-floor flat two streets from Elliot's Beach, with a partial sea view from the living room and master bedroom. Vitrified tile flooring, covered car park, and a genuinely quiet street. Walk to the beach in four minutes.",
    type: "APARTMENT",
    listingType: "SALE",
    price: 21500000,
    city: "Chennai",
    locality: "Besant Nagar",
    pincode: "600090",
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1580,
    furnishing: "Unfurnished",
    floor: "3 of 4",
    ageYears: 11,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Security", "Vaastu Compliant"],
    owner: "owner",
    photos: ["1600596542815-ffad4c1539a9", "1600585154340-be6161a56a0c", "1560448204-e02f11c3d0e2"],
  },
  {
    title: "2 BHK for rent near OMR, Thoraipakkam",
    description:
      "Practical 2 BHK on OMR with an easy commute to most IT parks on the stretch. Borewell plus metro water, covered two-wheeler and car parking, and a lift that works. Landlord prefers a family or working professionals.",
    type: "APARTMENT",
    listingType: "RENT",
    price: 26000,
    deposit: 156000,
    city: "Chennai",
    locality: "Thoraipakkam",
    pincode: "600097",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 940,
    furnishing: "Unfurnished",
    floor: "2 of 4",
    ageYears: 9,
    amenities: ["Lift", "Power Backup", "Covered Parking", "Security"],
    owner: "owner",
    photos: ["1502672260266-1c1ef2d93688", "1493809842364-78817add7ffb"],
  },
  {
    title: "Retail shop of 850 sq.ft on Jayanagar 4th Block",
    description:
      "Ground-floor retail unit on a high-footfall stretch of Jayanagar 4th Block, with a 22-foot frontage and a rolling shutter. Currently vacant and ready for fit-out. Suits F&B, a pharmacy or a branded apparel outlet.",
    type: "COMMERCIAL",
    listingType: "SALE",
    price: 29500000,
    city: "Bengaluru",
    locality: "Jayanagar",
    pincode: "560011",
    bedrooms: 0,
    bathrooms: 1,
    areaSqft: 850,
    ageYears: 18,
    amenities: ["Power Backup", "Security"],
    owner: "agent",
    photos: ["1497366754035-f200968a6e72", "1524758631624-e2822e304c36"],
  },
  {
    title: "5 BHK farmhouse on 1 acre near Lonavala",
    description:
      "Weekend home on a full acre with mature trees, a private pool and a covered outdoor dining deck. Five bedrooms across two blocks, all with attached bathrooms. Caretaker's quarters at the rear.\n\nAn hour and forty minutes from Mumbai on the expressway.",
    type: "VILLA",
    listingType: "SALE",
    price: 65000000,
    city: "Pune",
    locality: "Lonavala",
    pincode: "410401",
    bedrooms: 5,
    bathrooms: 5,
    areaSqft: 5200,
    furnishing: "Fully Furnished",
    ageYears: 7,
    amenities: ["Swimming Pool", "Covered Parking", "Security", "Park", "Power Backup", "Rain Water Harvesting"],
    featured: true,
    owner: "owner",
    photos: ["1613490493576-7fde63acd811", "1600596542815-ffad4c1539a9", "1600607687939-ce8a6c25118c"],
  },
  {
    title: "Corner plot of 3600 sq.ft in Sarjapur Road",
    description:
      "BMRDA-approved corner plot in a gated layout with an internal road network, streetlights and underground drainage already laid. Two sides open, north-east facing. Clear title with all approvals in hand.",
    type: "PLOT",
    listingType: "SALE",
    price: 16200000,
    city: "Bengaluru",
    locality: "Sarjapur Road",
    pincode: "562125",
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 3600,
    amenities: ["Security", "Park", "Rain Water Harvesting"],
    owner: "agent",
    photos: ["1500382017468-9049fed747ef", "1416879595882-3373a0480b5b"],
  },
];
