import { createReadStream } from "node:fs";
import { stat } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { NextResponse } from "next/server";
import { localUploadDir } from "@/lib/storage/local";

/** Only these extensions are ever served, mapped to their content type. */
const CONTENT_TYPES: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".avif": "image/avif",
};

/**
 * GET /api/files/:name — streams an image saved by the `local` storage driver.
 *
 * Needed because Next serves `public/` from a build-time snapshot: files
 * written there after the build are not reachable under `next start`. Serving
 * uploads through a route handler makes the local driver behave the same in
 * development and production.
 *
 * Filenames are generated by the driver (timestamp + random hex), so the strict
 * whitelist below rejects anything else outright — no traversal, no dotfiles,
 * no arbitrary reads.
 */
export async function GET(
  _request: Request,
  context: { params: Promise<{ name: string }> },
) {
  const { name } = await context.params;

  if (!/^[a-zA-Z0-9._-]+$/.test(name) || name.includes("..")) {
    return NextResponse.json({ ok: false, error: "Not found." }, { status: 404 });
  }

  const contentType = CONTENT_TYPES[path.extname(name).toLowerCase()];
  if (!contentType) {
    return NextResponse.json({ ok: false, error: "Not found." }, { status: 404 });
  }

  // Resolve and confirm the result is still inside the upload directory.
  const uploadDir = path.resolve(localUploadDir());
  const filePath = path.resolve(uploadDir, name);
  if (!filePath.startsWith(uploadDir + path.sep)) {
    return NextResponse.json({ ok: false, error: "Not found." }, { status: 404 });
  }

  let size: number;
  try {
    const stats = await stat(filePath);
    if (!stats.isFile()) throw new Error("not a file");
    size = stats.size;
  } catch {
    return NextResponse.json({ ok: false, error: "Not found." }, { status: 404 });
  }

  // Streamed rather than buffered, so a large image never sits in memory.
  const stream = Readable.toWeb(createReadStream(filePath)) as ReadableStream;

  return new NextResponse(stream, {
    headers: {
      "Content-Type": contentType,
      "Content-Length": String(size),
      // Filenames are unique per upload, so the bytes never change.
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
